In [1]:
import numpy as np

## NumPy Array Operation

In [18]:
arr=np.array([[1,2,3,4,5]])
print("Slicing:\n",arr[:5],"\n")
print("-Ve Slicing:\n",arr[::],"\n")

Slicing:
 [[1 2 3 4 5]] 

-Ve Slicing:
 [[1 2 3 4 5]] 



In [36]:
#Sales year wise id,2023,2024,2025
sales=np.array([[10,1000,1200,900],#Noodles
                [20,1100,1300,1000],#Pizza
                [30,1200,1400,1100]])#Icecream
print("Pizza Sales 2024:",sales[1,2],"\n")

print("Noodles Sales 2025:",sales[0,1:],"\n")

print("Sales of all items in 2024:",sales[:,1],"\n")

print("Sales data for 2023,2024:",sales[1,1:3],"\n")

print("Last two years sales for pizza and icecream:\n",sales[1:,2:],"\n")

Pizza Sales 2024: 1300 

Noodles Sales 2025: [1000 1200  900] 

Sales of all items in 2024: [1000 1100 1200] 

Sales data for 2023,2024: [1100 1300] 

Last two years sales for pizza and icecream:
 [[1300 1000]
 [1400 1100]] 



## Sorting

In [47]:
arr=np.array([[4,5,3,2,6,1]])
print("Sorting:\n",np.sort(arr),"\n")
Matrix=np.array([[3,2,1],[5,4,3],[7,9,8]])
print("Sorting Columns:\n",np.sort(Matrix,axis=0),"\n")
print("Sorting Rows:\n",np.sort(Matrix,axis=1),"\n")

Sorting:
 [[1 2 3 4 5 6]] 

Sorting Columns:
 [[3 2 1]
 [5 4 3]
 [7 9 8]] 

Sorting Rows:
 [[1 2 3]
 [3 4 5]
 [7 8 9]] 



## Filter

In [51]:
nums=np.array([10,3,2,5,6,7,8,9,1,4])
even=nums[nums%2==0]
print("Even numbers:\n",even,"\n")

#filter with mask

cgpa=np.array([9.5,8.5,3.5,4.5,5.5,8.74,9.25,7.75,6.25,5.75])
mask=cgpa>5.5
print("Mask:",mask)


Even numbers:
 [10  2  6  8  4] 

Mask: [ True  True False False False  True  True  True  True  True]


## Join

In [55]:
arr1=np.array([1,2,3,4])
arr2=np.array([9,8,7,6])
combined=np.concatenate([arr1,arr2])
print("Combined array:\n",combined,"\n")

Combined array:
 [1 2 3 4 9 8 7 6] 



In [62]:
matrix1=np.array([[1,2],
                  [5,6,]])
matrix2=np.array([[3,4],
                  [7,8]])
print("Vertical Stack:\n",np.vstack([matrix1,matrix2]),"\n")
print("Horizontal Stack:\n",np.hstack([matrix1,matrix2]),"\n")

Vertical Stack:
 [[1 2]
 [5 6]
 [3 4]
 [7 8]] 

Horizontal Stack:
 [[1 2 3 4]
 [5 6 7 8]] 



## Adding and Removing

In [78]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Slicing:\n",np.split(arr, 3),"\n")
#Append
print("Add",np.append(arr, [10,11,12]),"\n")
#Insert
print("Insert",np.insert(arr, 5, [10,11,12]),"\n")
#remove
print("Remove",np.delete(arr, 2),"\n")

#Adding and removing elements from 2D array

matrix=np.array([[1,2,3],
                [4,5,6]])
print("2D Array:\n",matrix,"\n")
print("Add Row:\n",np.insert(matrix, 1, [7,8,9], axis=0),"\n")
print("Add Column:\n",np.insert(matrix, 1, [7,8], axis=1),"\n")
print("Remove Row:\n",np.delete(matrix, 1, axis=0),"\n")
print("Remove Column:\n",np.delete(matrix, 1, axis=1),"\n")
#how to use fancy index and np.where in NumPy



Slicing:
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])] 

Add [ 1  2  3  4  5  6  7  8  9 10 11 12] 

Insert [ 1  2  3  4  5 10 11 12  6  7  8  9] 

Remove [1 2 4 5 6 7 8 9] 

2D Array:
 [[1 2 3]
 [4 5 6]] 

Add Row:
 [[1 2 3]
 [7 8 9]
 [4 5 6]] 

Add Column:
 [[1 7 2 3]
 [4 8 5 6]] 

Remove Row:
 [[1 2 3]] 

Remove Column:
 [[1 3]
 [4 6]] 



## Fancy Indexing and `np.where`

**Fancy indexing** selects multiple elements using a list or array of indices. `np.where` can return matching indices or choose values based on a condition.
import numpy as np

# Fancy indexing with a 1D array
scores = np.array([72, 91, 65, 88, 79])
selected = scores[[1, 3, 4]]
print("Scores at positions 1, 3, and 4:", selected)

# Fancy indexing with a 2D array: select rows and columns together
sales = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("Selected rows 0 and 2:\n", sales[[0, 2]])
print("Selected values at (row, column) pairs:", sales[[0, 2], [1, 0]])

# np.where(condition) returns the indices where the condition is True
even_positions = np.where(scores % 2 == 0)
print("Positions of even scores:", even_positions[0])
print("Even scores:", scores[even_positions])

# np.where(condition, value_if_true, value_if_false) replaces values by condition
result = np.where(scores >= 80, "Pass", "Needs improvement")
print("Result:", result)

In [79]:
import numpy as np

# Fancy indexing with a 1D array
scores = np.array([72, 91, 65, 88, 79])
selected = scores[[1, 3, 4]]
print("Scores at positions 1, 3, and 4:", selected)

# Fancy indexing with a 2D array: select rows and columns together
sales = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("Selected rows 0 and 2:\n", sales[[0, 2]])
print("Selected values at (row, column) pairs:", sales[[0, 2], [1, 0]])

# np.where(condition) returns the indices where the condition is True
even_positions = np.where(scores % 2 == 0)
print("Positions of even scores:", even_positions[0])
print("Even scores:", scores[even_positions])

# np.where(condition, value_if_true, value_if_false) replaces values by condition
result = np.where(scores >= 80, "Pass", "Needs improvement")
print("Result:", result)

Scores at positions 1, 3, and 4: [91 88 79]
Selected rows 0 and 2:
 [[10 20 30]
 [70 80 90]]
Selected values at (row, column) pairs: [20 70]
Positions of even scores: [0 3]
Even scores: [72 88]
Result: ['Needs improvement' 'Pass' 'Needs improvement' 'Pass' 'Needs improvement']


## Mathematical Operation

In [108]:
arr1=np.array([15,20,25,30])
arr2=np.array([5,10,15,10])

print("Addition:",np.add(arr1,arr2),"\n")
print("Subtraction:",np.subtract(arr1,arr2),"\n")
print("Multiplication:",np.multiply(arr1,arr2),"\n")
print("Division:",np.divide(arr1,arr2),"\n")

print("Dot Product:",np.dot(arr1,arr2),"\n")
print("Power:",np.power(arr1,2),"\n")
print("Square Root:",np.sqrt(arr2),"\n")

Addition: [20 30 40 40] 

Subtraction: [10 10 10 20] 

Multiplication: [ 75 200 375 300] 

Division: [3.         2.         1.66666667 3.        ] 

Dot Product: 950 

Power: [225 400 625 900] 

Square Root: [2.23606798 3.16227766 3.87298335 3.16227766] 

