## Numpy Array and Basic

### Arrays
* An array is defined as a collection of items that are stored at contiguous memory location.
* It is a container which can hold a fixed amount of items and these items should be the same type.

In [23]:
import numpy as np
import time  as t

In [21]:

#1d array
arr_1d=np.array([10,20,30])
print("1D Array:",arr_1d)
#2d array
arr_2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("2D Array:\n",arr_2d)

1D Array: [10 20 30]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### List vs NumPy Array

In [29]:
# List multipication
list_cost=[10,20,30,40,50]
print("list of sales:",list_cost*2)

Start=t.time()
list_nums=[i*2 for i in range(1000000)]
print("Time taken by list:",t.time()-Start)

# Array multipication
array_cost=np.array([10,20,30,40,50])
print("array of sales:",array_cost*2)

Start=t.time()
array_num=np.arange(100000)*2
print("Time taken by list:",t.time()-Start)

list of sales: [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
Time taken by list: 0.15341401100158691
array of sales: [ 20  40  60  80 100]
Time taken by list: 0.0004706382751464844


## NumPy Array from scratch

In [50]:
#zeros
zeros=np.zeros((3,3))
print(zeros,"\n")

#ones
ones=np.ones((3,3))
print(ones,"\n")

#full array
full=np.full((3,3),4)
print(full,"\n")

#random
random=np.random.random((2,2))*100
print(random,"\n")

#Range
range=np.arange(10,21,0.01)
print(range,"\n")


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[4 4 4]
 [4 4 4]
 [4 4 4]] 

[[68.64195872 24.54862339]
 [ 1.66588829 29.50313579]] 

[10.   10.01 10.02 ... 20.97 20.98 20.99] 

